apiVersion: v1
kind: Service
metadata:
  name: ammit-report-api
  labels:
    app: ammit-report-api
spec:
  type: ClusterIP
  selector:
    app: ammit-report-api
  ports:
    - name: http          # named port referenced by the ServiceMonitor
      port: 8080
      targetPort: http
